source 'https://rubygems.org'
gem 'sinatra', '1.4.5'
gem 'thin', '1.6.2'
gem 'haml', '4.0.5'
gem 'aws-sdk', '1.57.0'
gem 'rubocop', '0.27.1'
gem 'rspec-rails', '2.13'
gem 'rubocop-rspec', '1.1'
gem 'rake'
gem 'dynamoid'
gem 'modularity', '>=2'
